# Application name & port
server.port=8008
server.ssl.enabled=true

# SSL keystore (FROM RESOURCES)
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=StrongPass123!
server.ssl.key-alias=aqark-api



# ====== Database (SQL Server) ======
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AQARK_RENT_MANAGEMENT;encrypt=true;trustServerCertificate=true
spring.datasource.username=app_root
spring.datasource.password=app_root
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ====== JPA / Hibernate ======
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# (Hibernate can auto-detect, but set explicitly for clarity)
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Logging (for debugging queries)
logging.level.org.hibernate.SQL=DEBUG

# Security default login (Spring Security auto-config)
spring.security.user.name=admin
spring.security.user.password=admin

# File upload base directory
upload.directory=C:\\MyApps\\AQARK_RENT_MANAGEMENT\\Uploads

# Values
folder.buildings=buildings
folder.building=building
folder.rooms=room
folder.flat=flat
folder.home=home


flat.link.src=http://localhost:8008/api/images/flat/
building.link.src=http://localhost:8008/api/images/buildings/
room.link.src=http://localhost:8008/api/images/room/


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://localhost:9443/oauth2/jwks
